[build]
  command = """
    cd /opt/build/repository &&
    flutter config --enable-web &&
    flutter clean &&
    flutter pub get &&
    flutter build web
  """
  publish = "build/web"

[build.environment]
  FLUTTER_VERSION = "3.22.0"
  PUB_CACHE = "/opt/buildhome/.pub-cache"

[[plugins]]
  package = "netlify-plugin-flutter"