name: workstudy
description: "A Flutter project for managing student work hours, reports, and exports."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  provider: ^6.1.2
  animations: ^2.0.10
  intl: ^0.19.0
  pdf: ^3.11.0
  printing: ^5.13.3
  excel: ^4.0.3
  path_provider: ^2.1.4
  fluttertoast: ^8.2.5
  file_picker: ^8.0.0
  firebase_core: ^3.15.2
  firebase_auth: ^5.7.0
  cloud_firestore: ^5.6.12
  google_fonts: ^4.0.4
  google_generative_ai: ^0.2.3
  uuid: ^4.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
